package com.zhao;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import com.mchange.v2.c3p0.ComboPooledDataSource;
import com.mchange.v2.c3p0.DataSources;

public class JDBCUtil {
	
	public static void save(dept) throws Exception{
		String sql = "insert into t_dept (deptId,depatName)values (?,?)";
		ComboPooledDataSource c = new ComboPooledDataSource();
		c.setJdbcUrl("jdbc:mysql://127.0.0.1:3306/hibernate");
		c.setUser("root");
		c.setPassword("74110");
		c.setDriverClass("com.mysql.jdbc.Driver");
		try {
			Connection connection = c.getConnection();
			System.out.println(connection);
			PreparedStatement p = connection.prepareStatement(sql);
			p.setInt(1, dept.get);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
		System.out.println("error..........");
		}
		DataSources.destroy(c);
	}

}
